name: Auto-merge PR approuvées

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    if: github.event.review.state == 'approved' || github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge si conditions remplies
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;

            try {
              // Vérifier si la PR est approuvée
              const { data: reviews } = await github.rest.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              });
              
              const approved = reviews.some(review => review.state === 'APPROVED');
              
              if (approved && !pr.labels.some(label => ['work-in-progress', 'do-not-merge'].includes(label.name))) {
                await github.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  merge_method: 'squash'
                });
                console.log('PR mergée automatiquement');
              }
            } catch (error) {
              console.log('Auto-merge échoué:', error.message);
            }
